app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    profile = db.Column(db.String)
    prof_pic = db.Column(db.String())
    pitch = db.relationship("Pitch", backref="user", lazy="dynamic")
    comment = db.relationship("Comment", backref ="user", lazy="dynamic")
    pass_hash = db.Column(db.String(255))

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    @property
    def password(self):
        raise AttributeError('Stick to your lane!')
    
    @password.setter
    def password(self,password):
        self.pass_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_hash, password)

    def get_pitches(self):
        user = User.query.filter_by(id = self.id).first()
        return user.pitch
    
    def get_comments(self):
        user = User.query.filter_by(id = self.id).first()
        return user.comment

class Pitch(db.Model):
    '''
    User class to define pitch objects
    '''
    __tablename__ = "pitches"
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    name = db.Column(db.String)
    category = db.Column(db.String)
    pitch = db.Column(db.String(255))
    upvotes = db.Column(db.Integer)
    downvotes = db.Column(db.Integer)
    comments = db.relationship("Comment", backref="pitch", lazy="dynamic")
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    def pitch_comments(self):
        pitch = Pitch.query.filter_by(id = self.id).first()
        comments = Comment.query.filter_by(pitch_id = pitch.id).order_by(Comment.date_created.desc())

class Comment(db.Model):
    '''
    Defines comment objects
    '''
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    comment = db.Column(db.String(255))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class AddPitch(FlaskForm):
    name = StringField("Title", validators=[Required()])
    category = SelectField("category",choices=[("Business", "Business"),("Funny","Funny"),("Pick-up lines","Pick-up lines"),("Promotion","Promotion")])
    content = TextAreaField("Pitch", validators=[Required()])
    submit = SubmitField("Pitch!")

class AddComment(FlaskForm):
    content = TextAreaField("Add comment")
    submit = SubmitField("Comment")

class UpdateProfile(FlaskForm):
    profile = TextAreaField("Tell us about you", validators = [Required()])
    submit = SubmitField("Add")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"
photos = UploadSet('photos', IMAGES)
mail = Mail()

def create_app(config_name):

    #Initializing application
    app = Flask(__name__)

    #Creating app configurations
    app.config.from_object(config_options[config_name])

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')
    
    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #Configure UploadSet
    configure_uploads(app,photos)




    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask import render_template, request, redirect,flash, url_for,abort
from ..models import User,Pitch,Comment
from . import main
from flask_login import login_required
from .forms import UpdateProfile,AddComment,AddPitch
from .. import db,photos
import datetime

#views
@main.route('/')
def index():
    '''
    Returns index page and it's data
    '''
    pitches = Pitch.query.all()
    title = "Speed Pitching"
    return render_template('index.html', pitches=pitches, title = title)

@main.route("/pitches/<category>")
def categories(category):
    pitches = None
    if category == "all":
        pitches = Pitch.query.order_by(Pitch.date_created.desc())
    else:
        pitches = Pitch.query.filter_by(category=category).order_by(Pitch.date_created.desc()).all()

    return render_template("pitches.html",pitches=pitches,title=category.capitalize())

@main.route('/user/<username>')
def profile(username):
    user = User.query.filter_by(username = username).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<username>/update', methods = ['GET', 'POST'])
@login_required
def update_profile(username):
    user = User.query.filter_by(username = username).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.profile = form.profile.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', username=user.username))

    return render_template('profile/update.html', form=form)

@main.route('/user/<username>/update/pic', methods=['POST'])
@login_required
def update_pic(username):
    user = User.query.filter_by(username=username).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.prof_pic = path
        db.session.commit()
    return redirect(url_for('main.profile',username=username))

@main.route("/<username>/add_pitch", methods = ["GET","POST"])
@login_required
def add_pitch(username):
    form = AddPitch()
    user = User.query.filter_by(username = username).first()
    if user is None:
        abort(404)
    title = "Add Pitch"
    if form.validate_on_submit():
        name = form.name.data
        category = form.category.data 
        content = form.content.data
        date_created= datetime.datetime.now()

        new_pitch = Pitch(name = name, category = category, pitch = content, user = user, date_created = date_created)
        new_pitch.save_pitch()  
        pitches = Pitch.query.all()
        
        return redirect(url_for("main.categories",category = category))
    return render_template("add_pitch.html",pitch_form = form, title = title)

app/templates/add_pitch.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock%}

{% block content %}
<div class = "container">
    {{wtf.quick_form(pitch_form)}}
</div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!--Navbar block-->
{% block navbar %}  
    {% include 'navbar.html' %}
{% endblock %}

<!--Content Block-->
{% block content %}

{% endblock %}

app/templates/create_pitch.html
{% extends "base.html" %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>WHOOPS!!! We can't find that page:(</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block styles%}
{{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{%block content%}
    <div class = "container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
          
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img src="../static/images/create.png"  class="img img-responsive" style="width:100%;">
              </div>
          
              <div class="item">
                <img src="../static/images/share.png"  class="img img-responsive" style="width:100%;">
              </div>
          
              <div class="item">
                <img src="../static/images/comment.png"  class="img img-responsive" style="width:100%;">
              </div>
            </div>
          
            <!-- Left and right controls -->
            <div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
        
        {% if current_user.is_authenticated%}
            <h1>YOUR PITCHES</h1>
            {% for pitch in pitches %}
            <div class = "well">
                <ul>
                    <li>{{pitch.name | upper}}</li>
                    <p>{{pitch.category}}</p>
                    <p>{{pitch.pitch}}</p>
                    <p>posted on: {{pitch.date_created}}</p>
                    <p>Posted by: {{pitch.username}}</p>
                </ul>
            </div>
            {% endfor %}
            
        {% else %}
        <div class = "content">
            <h1>POPULAR PITCHES</h1>
            <div class = "well">
                <h2><b>FUNNY</b></h2>
                <h4>KNOCK KNOCK</h4>
                <p>Knock knock<br/>
                    Who's there?<br/>
                    Tuna<br/>
                    Tuna who?<br/>
                    <b>Tonight we are dunda? Dundaing</b> 
                </p>
            </div>

            <div class="well">
                <h2><b>BUSINESS</b></h2>
                <h4>ORIGINALITY</h4>
                <p>It is better to fail in originality than to succeed in imitation</p>




                

            </div>
                
        </div>
        {% endif %}
    </div>
{% endblock%}
{% block scripts %}
    <script src="{{url_for('static',filename='js/jquery.js')}}"></script>
    {{super()}}
{% endblock %}

app/templates/navbar.html
<div class = "navbar navbar-inverse" role = "navigation">
    <div class = "container-fluid">
        <div class = "navbar-header" style = "background-color: black">
            <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse">
                <span class = "sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class = "navbar-brand" href = "/">SPEED PITCHING</a>
        </div>
        <div class = "navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('main.profile',username=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('main.add_pitch', username = current_user.username)}}">Add Pitch</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Log Out</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">Log In</a></li>
                        {%endif%}
                      </ul>
        </div>
          
    </div>
</div>

app/templates/pitches.html
{% extends "base.html" %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock%}

{% block content %}
    <div class="container">
        {% for pitch in pitches%}
        <h1>{{pitch.category | upper}}</h1>
        <div class="info">
            <p>{{pitch.name | upper}}</p>
            <p>{{pitch.pitch}}</p>
            <p>Pitched by: </p>


        </div>
        {% endfor %}
    </div>
{% endblock %}
        

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.profile %}
      <p> {{user.profile}}</p>
    {%else%}
      <p> {{user.username| capitalize}} User has no bio </p>
    {% endif %}

    <!--Update profile-->
    <div class = "update">
        {% if user == current_user %}
            <a href="{{url_for('main.update_profile',username=user.username)}}">Edit profile</a>
        {% endif %}  
    </div>
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.prof_pic %}
    <img src="{{url_for('static',filename=user.prof_pic)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture available</p>
    {% endif %}

      {% if user == current_user%}
      <form action="{{url_for('main.update_pic', username=user.username)}}" method="post" enctype="multipart/form-data">
        <input type="file" name="photo" class="form-control" required>
        <input type="submit">
      </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}